-- Migration: v1.1.0 -> v1.2.0
-- Adds PLACES table and PERSON_PLACES join table.

-- Create PLACES table with auto-incrementing ID, PLACE NAME, and CITY.
CREATE TABLE IF NOT EXISTS PLACES (
  ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  CITY VARCHAR(255) NOT NULL
);

-- Create PERSON_PLACES join table linking PEOPLE and PLACES.
CREATE TABLE IF NOT EXISTS PERSON_PLACES (
  PERSON_ID BIGINT NOT NULL,
  PLACE_ID BIGINT NOT NULL,
  CONSTRAINT fk_person_places_person FOREIGN KEY (PERSON_ID) REFERENCES PEOPLE(ID),
  CONSTRAINT fk_person_places_place FOREIGN KEY (PLACE_ID) REFERENCES PLACES(ID)
);
